# Generated by Django 4.2.9 on 2024-01-16 04:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('isFurnished', models.BooleanField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('property_type', models.CharField(choices=[('R', 'Rent'), ('S', 'Sale')], default='R', max_length=1)),
                ('living_room', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('bath_room', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('bed_room', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
            ],
        ),
    ]
