# Generated by Django 4.2.9 on 2024-01-16 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='isFurnished',
            new_name='is_furnished',
        ),
    ]
