# Generated by Django 4.2.9 on 2024-01-17 15:05

from django.db import migrations, models
import properties.models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0003_property_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="image_url",
            field=models.ImageField(
                blank=True, null=True, upload_to=properties.models.upload_to
            ),
        ),
    ]
